/* the sheet: what a node holds, spread open from the node itself */
function exList(t){const p=String(t||"").split(/\s*…\s*/).map(x=>x.trim()).filter(x=>x.length>2).slice(0,5);return p.length?`<ol class="ex">${p.map(x=>`<li>${esc(x)}</li>`).join("")}</ol>`:""}
function sheetHTML(w,id){const S=w.steps||[],M=w.map||{},P=M.pages||[],C=M.calls||[],si=x=>`<div class="si">${x}</div>`;
 const dn=i=>S[i]?`Desk ${ROMAN[i]} · ${ROLE[S[i].role]}${S[i].focus?` · ${esc(S[i].focus)}`:""}`:"";
 const page=p=>`<div class="pg si"><h5>${esc(p.title||hostOf(p.url))}</h5><div class="mt">${p.date?`<span class="num">${esc(p.date)}</span>`:""}<span class="age${(ageOf(p.date)??0)>(freshDays()||1e9)?" old":""}">${ageText(ageOf(p.date))}</span>${S[p.i]?`<span>${dn(p.i)}</span>`:p.i===-1?"<span>Decision agent’s check</span>":""}${p.q?`<span>“${esc(p.q)}”</span>`:""}</div>${exList(p.ex)}<a class="go" href="${esc(p.url)}" target="_blank" rel="noopener">Open the page ↗</a></div>`;
 if(id.startsWith("s:")){const hh=id.slice(2),L=P.filter(p=>hostOf(p.url)===hh);if(!L.length)return "";return si(`<span class="k cap">Source</span><h4>${esc(hh)}</h4><div class="mt"><span>${L.length} page${L.length>1?"s":""} pulled</span><span>via Exa</span></div>`)+L.map(page).join("")}
 if(id.startsWith("u:")){const p=P.find(x=>x.url===id.slice(2));if(!p)return "";return si(`<span class="k cap">Source · ${esc(hostOf(p.url))}</span>`)+page(p).replace('class="pg si"','class="si" style="margin-top:6px"')}
 if(id==="more"){const rest=hostsOf(P).slice(SITES);return si(`<span class="k cap">Sources</span><h4>${rest.length} more site${rest.length>1?"s":""}</h4>`)+si(`<ul class="ql">${rest.map(o=>`<li><span class="num">${o.n}</span><button class="lnk" data-sheet="s:${esc(o.h)}">${esc(o.h)}</button></li>`).join("")}</ul>`)}
 if(id==="c"){const hs=hostsOf(P);return si(`<span class="k cap">Connector</span><h4>Exa</h4><div class="mt"><span>web_search_exa · web_fetch_exa</span><span>${C.length} call${C.length>1?"s":""}</span><span>${hs.length} site${hs.length>1?"s":""}</span></div>`)+si(`<span class="k2 cap">Calls</span><ul class="ql">${C.map(c=>`<li><span class="num">${mmss(c.t)}</span><span><b class="dk">${ROMAN[c.i]||""}.</b> ${c.fetch?"Read ":""}${c.q.map(x=>c.fetch?esc(x):`“${esc(x)}”`).join(", ")}</span></li>`).join("")}</ul>`)+(hs.length?si(`<span class="k2 cap">Sites</span><ul class="ql">${hs.map(o=>`<li><span class="num">${o.n}</span><button class="lnk" data-sheet="s:${esc(o.h)}">${esc(o.h)}</button></li>`).join("")}</ul>`):"")}
 if(id==="o"){const th=M.thinking||[];return si(`<span class="k cap">Orchestrator · Opus 5.5, high effort</span><h4>${esc(M.kind?cap1(M.kind):"Deliberation")}</h4>`)+(th.length?si(`<span class="k2 cap">Deliberation</span><div class="dl2">${th.map(t=>`<p>${esc(t)}</p>`).join("")}</div>`):"")+(M.rationale?si(`<p class="tk">${esc(M.rationale)}</p>`):"")+(S.length?si(`<span class="k2 cap">Staffing</span><ul class="ql">${S.map((s,i)=>`<li><span class="num">${ROMAN[i]}.</span><button class="lnk" data-sheet="a${i}">${ROLE[s.role]}${s.focus?" · "+esc(s.focus):""}</button></li>`).join("")}</ul>`):"")}
 if(id==="v"){const t=ledgerStats(w.ledger);return si(`<span class="k cap">Decision agent</span><h4>Staffing, then truth</h4><p class="tk">It took the orchestrator's deliberation and staffed ${words(S.length).toLowerCase()} desk${S.length===1?"":"s"} at the effort each needed. When the desks filed, it weighed every claim against the pages they read${(C.some(c=>c.i===-1))?" and ran its own checks on the web":""}.</p>${t.n?`<div class="mt"><span>${t.g} grounded</span>${t.q?`<span>${t.q} qualified</span>`:""}${t.u?`<span>${t.u} open</span>`:""}</div>`:""}`)+(t.n?si(ledgerHTML(w,true)):si(`<p class="empty2">This run predates the claims ledger.</p>`))}
 if(id==="doc"){const d=w.doc;if(!d)return "";if(d.error)return si(`<span class="k cap">Document held</span><h4>${esc(DOCT[d.type]||"Document")}</h4><p class="tk">${esc(d.error)}</p>`);return si(`<span class="k cap">Document · kernel ${esc(d.kernel||"")}</span><h4>${esc(d.title)}</h4><div class="mt"><span>${d.pages} pages</span><span>Verified by the kernel builder</span></div><ul class="ql">${(d.checks||[]).map(c=>`<li><span class="num">✓</span><span>${esc(c[0])}</span></li>`).join("")}</ul>`)+si(`<button class="btn2" data-docopen-sheet>Open the document</button>`)}
 if(id==="ans"){const au=w.ledger&&w.ledger.audit,t=ledgerStats(w.ledger);return si(`<span class="k cap">Answer</span><h4>${t.n?`${t.g} of ${t.n} claims grounded`:"Filed"}</h4><p class="tk">The answer may only state what the ledger supports; estimates are marked as such, and each figure carries its claim number.</p>`)+(au?si(`<span class="k2 cap">Audit</span>${au.flags?`<ul class="ql">${(au.items||[]).map(x=>`<li><span class="num">—</span><span>“${esc(x.quote)}” <small style="color:var(--mute)">${esc(x.why||"")}</small></span></li>`).join("")}</ul><p class="tk">These lines were qualified or removed before filing.</p>`:`<p class="tk">Every factual statement was backed by the ledger.</p>`}`):"")}
 if(id.startsWith("k:")){const Lg=w.ledger,c=Lg&&(Lg.claims||[]).find(x=>String(x.id)===id.slice(2));if(!c)return "";const pg=(c.urls||[]).map(u=>P.find(p=>p.url===u)).filter(Boolean);
  return si(`<span class="k cap">Claim c${c.id}</span><h4>${esc(c.text)}</h4><div class="mt"><span class="vchip v-${c.v}">${VL[c.v]||c.v}</span>${c.conf!=null?`<span class="num">${Math.round(c.conf*100)}% confidence</span>`:""}${S[c.desk]?`<span>${dn(c.desk)}</span>`:""}</div>${c.note?`<p class="tk">${esc(c.note)}</p>`:""}`)+(pg.length?pg.map(page).join(""):si(`<p class="empty2">${c.v==="derived"?"Computed from other claims or your own figures.":"No page backs this claim. Treat it as an estimate."}</p>`))}
 if(/^a\d+$/.test(id)){const i=+id.slice(1),s=S[i];if(!s)return "";const q=C.filter(c=>c.i===i),hs=hostsOf(P.filter(p=>p.i===i));
  return si(`<span class="k cap">Desk ${ROMAN[i]} · ${ROLE[s.role]}</span><h4>${esc(s.focus||s.task)}</h4>${s.focus?`<p class="tk">${esc(s.task)}</p>`:""}<div class="mt"><span>${TIERS[s.tier].w} effort</span>${s.ms?`<span class="num">${fmt(s.ms)}</span>`:s._live?"<span>Working</span>":""}${s.v?`<span class="${s.v}">${s.v==="pass"?"Passed review":"Returned"}</span>`:""}${s.after&&s.after.length?`<span>After ${s.after.map(n=>"desk "+ROMAN[n-1]).join(" and ")}</span>`:""}</div>${s.why?`<p class="tk" style="font-size:12px;color:var(--soft)">${esc(cap1(s.why))}</p>`:""}`)
   +(q.length?si(`<span class="k2 cap">Searches</span><ul class="ql">${q.map(c=>`<li><span class="num">${mmss(c.t)}</span><span>${c.fetch?"Read ":""}${c.q.map(x=>c.fetch?esc(x):`“${esc(x)}”`).join(", ")}</span></li>`).join("")}</ul>`):"")
   +(hs.length?si(`<span class="k2 cap">Sites it drew on</span><ul class="ql">${hs.map(o=>`<li><span class="num">${o.n}</span><button class="lnk" data-sheet="s:${esc(o.h)}">${esc(o.h)}</button></li>`).join("")}</ul>`):"")
   +si(`<span class="k2 cap">Notes</span><div class="nt2">${esc(s.out||(s._live?"Writing…":"No notes filed."))}</div>`)}
 return ""}
const sheetTitle=B=>(B.querySelector("h4")?.textContent||B.querySelector(".k,.cap")?.textContent||"Back").trim().slice(0,48);
function sheetPeek(){const sh=$("#sheet"),st=sh._stack||[],P=$("#sheetP");P.innerHTML=st.map((x,i)=>`<button type="button" class="spk" data-spop="${i}" style="--d:${st.length-i}"><svg viewBox="0 0 12 12" fill="none" stroke="currentColor" stroke-width="1.2"><path d="M7.5 2.5 4 6l3.5 3.5"/></svg><span>${esc(x.title)}</span></button>`).join("");sh.classList.toggle("deep",st.length>0)}
function sheetSwap(html,dir){const B=$("#sheetB");B.innerHTML=html;B.scrollTop=0;B.querySelectorAll(".si").forEach((x,i)=>x.style.animationDelay=(.06+i*.05).toFixed(2)+"s");if(!reduce)B.animate(dir>0?[{opacity:0,transform:"translateX(18px) scale(.985)"},{opacity:1,transform:"none"}]:[{opacity:0,transform:"translateX(-14px) scale(.985)"},{opacity:1,transform:"none"}],{duration:SPRING?SPRING.soft.ms:420,easing:SPRING?SPRING.soft.e:"cubic-bezier(.2,.8,.2,1)"})}
function sheetPush(w,id){const sh=$("#sheet"),B=$("#sheetB"),st=sh._stack=sh._stack||[];if(id===sh._id)return;const at=st.findIndex(x=>x.id===id);if(at>=0){sheetPop(at);return}const html=sheetHTML(w,id);if(!html)return;
 st.push({id:sh._id,html:B.innerHTML,top:B.scrollTop,title:sheetTitle(B)});if(st.length>4)st.shift();sh._id=id;sheetPeek();sheetSwap(html,1)}
function sheetPop(to){const sh=$("#sheet"),st=sh._stack||[];if(!st.length)return false;const i=to==null?st.length-1:to,x=st[i];st.length=i;sh._id=x.id;sheetPeek();sheetSwap(x.html,-1);$("#sheetB").scrollTop=x.top;return true}
document.addEventListener("click",e=>{const p=e.target.closest("[data-spop]");if(p){e.stopPropagation();sheetPop(+p.dataset.spop)}},true);
function openSheet(w,id,anchor){const sh=$("#sheet");if(!w||!anchor)return;if(sh.classList.contains("open")&&anchor.closest&&anchor.closest("#sheet")){sheetPush(w,id);return}if(sh._stack&&sh._stack.length){sh._stack=[];sheetPeek();if(sh._id!==id)sh._id=null}else{sh._stack=[];sheetPeek()}if(sh.classList.contains("open")&&sh._id===id&&sh._w===w){closeSheet();return}acctMenu(false);const html=sheetHTML(w,id);if(!html)return;closeCtx();menu(false);setMenu(false);
 document.querySelectorAll(".map .sel").forEach(x=>x.classList.remove("sel"));if(anchor.closest&&anchor.closest(".map"))anchor.classList.add("sel");
 sh._w=w;sh._id=id;sh.style.transition="none";sh.classList.remove("open");$("#sheetB").innerHTML=html;$("#sheetB").scrollTop=0;$("#sheetB").querySelectorAll(".si").forEach((x,i)=>x.style.animationDelay=(.1+i*.06).toFixed(2)+"s");
 const r=anchor.getBoundingClientRect(),sw=Math.min(380,innerWidth-24);sh.style.width=sw+"px";const hh=sh.offsetHeight;
 let x=r.right+12+sw<=innerWidth-12?r.right+12:r.left-12-sw>=12?r.left-12-sw:(innerWidth-sw)/2,y=Math.max(12,Math.min(innerHeight-hh-12,r.top+r.height/2-90));
 sh.style.left=x+"px";sh.style.top=y+"px";sh.style.setProperty("--ox",(r.left+r.width/2-x).toFixed(0)+"px");sh.style.setProperty("--oy",(r.top+r.height/2-y).toFixed(0)+"px");
 void sh.offsetWidth;sh.style.transition="";requestAnimationFrame(()=>sh.classList.add("open"));setTimeout(()=>$("#sheetX").focus({preventScroll:true}),80)}
function closeSheet(){const sh=$("#sheet");if(!sh||!sh.classList.contains("open"))return;sh._stack=[];setTimeout(sheetPeek,450);sh._id=null;sh.classList.remove("open");document.querySelectorAll(".map .sel").forEach(x=>x.classList.remove("sel"))}
$("#sheetX").onclick=closeSheet;
document.addEventListener("pointerdown",e=>{if($("#sheet").classList.contains("open")&&!e.target.closest("#sheet,[data-node],[data-sheet],a[data-src],[data-claim]"))closeSheet()});

