let GOOID=0;
function miniSVG(w,live,seenIds,narrow){let {N,E}=graphOf(w);if(narrow){const ns=N.filter(n=>n.col===4).reduce((a,n)=>a+(n.kind==="more"?+(String(n.t1).match(/\d+/)||[0])[0]:1),0);N=N.filter(n=>n.col!==4).map(n=>n.kind==="conn"&&ns?{...n,num:0,t1:"",_ns:ns}:n);E=E.filter(e=>N.some(n=>n.id===e.b)&&N.some(n=>n.id===e.a))}if(N.length<2)return "";const cols=[[],[],[],[],[]];N.forEach(n=>{if(n.kind!=="ans"&&n.kind!=="doc"&&cols[n.col])cols[n.col].push(n)});N.filter(n=>n.kind==="ans"||n.kind==="doc").forEach(n=>cols[1].push(n));
 const X=narrow?[10,96,190,292,0]:[16,150,300,470,560],RH=24,mx=Math.max(3,...cols.map(c=>c.length)),H=Math.min(250,mx*RH+22),P={};
 cols.forEach((c,ci)=>{const tot=(c.length-1)*RH;c.forEach((n,i)=>P[n.id]=[X[ci],Math.round(H/2-tot/2+i*RH)])});
 const cur=(a,b,back)=>{const [x1,y1]=P[a],[x2,y2]=P[b];const dx=Math.max(24,Math.abs(x2-x1)*.5),o=back?4:0;return `M${x1} ${y1+o}C${x1+(x2>x1?dx:-dx)} ${y1+o},${x2-(x2>x1?dx:-dx)} ${y2+o},${x2} ${y2+o}`};
 const gid="goo"+(++GOOID),on=new Set(),nb=new Set(seenIds?N.filter(n=>!seenIds.has(n.id)).map(n=>n.id):[]);let ed="",bd="";
 E.forEach(e=>{if(!P[e.a]||!P[e.b])return;const back=/>v$/.test(e.id)&&e.a[0]==="a",d=cur(e.a,e.b,back),act=live&&e.on;if(act){on.add(e.a);on.add(e.b)}
  ed+=`<path class="me${act?" on":""}${e.dep?" dep":""}${back?" bk":""}${nb.has(e.a)||nb.has(e.b)?' ne" pathLength="1':""}" d="${d}"/>`;if(act&&!nb.has(e.a)&&!nb.has(e.b))for(let q=0;q<2;q++)bd+=`<circle class="bd${back?" bk":""}" r="1.7"><animateMotion dur="${back?1.3:1}s" begin="-${q*(back?.65:.5)}s" repeatCount="indefinite" path="${d}"/></circle>`});
 let dots="",rings="",labs="";N.forEach(n=>{const p=P[n.id];if(!p)return;const fresh=seenIds&&!seenIds.has(n.id);seenIds&&seenIds.add(n.id);const r=n.kind==="orch"||n.kind==="arb"?4.5:n.kind==="site"||n.kind==="more"?2.6:3.6,st=live&&n.st==="on";
  const c=`<circle class="md k-${n.kind}${n.role?" r-"+n.role:""} s-${n.st}${fresh?" nb":""}" cx="${p[0]}" cy="${p[1]}" r="${r}"/>`;if(n.kind==="site"||n.kind==="more")rings+=c;else dots+=c;
  labs+=`<g class="mn${st?" on":""}${fresh?" nb":""}" data-sheet="${esc(n.id)}" tabindex="0" role="button" aria-label="${esc(MLAB(n))}">${st?`<circle class="halo" cx="${p[0]}" cy="${p[1]}" r="${r+3}"/>`:""}<circle class="hit" cx="${p[0]}" cy="${p[1]}" r="11"/><text x="${p[0]+(n.col===4?7:8)}" y="${p[1]+3.4}">${esc(MLAB(n))}${n.num>1?`<tspan class="nm"> ${n.num}</tspan>`:""}</text></g>`});
 return `<svg viewBox="0 0 ${narrow?440:700} ${H}" preserveAspectRatio="xMinYMid meet" style="height:${H}px"><defs><filter id="${gid}" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur in="SourceGraphic" stdDeviation="1.6" result="b"/><feColorMatrix in="b" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 16 -6" result="g"/><feComposite in="SourceGraphic" in2="g" operator="atop"/></filter></defs><g class="eds">${ed}</g>${rings}<g filter="url(#${gid})">${dots}${bd}</g><g class="lbs">${labs}</g></svg>`}
function miniDraw(run,w,live){const m=run.querySelector(".mini");if(!m)return;const {N,E}=graphOf(w),sig=N.map(n=>n.id+n.st).join()+"|"+E.map(e=>e.on?1:0).join("")+(live?1:0);const nw=m.clientWidth>0&&m.clientWidth<520;if(m._sig===sig+nw)return;m._sig=sig+nw;if(0)m._sig=sig;m._ids=m._ids||new Set();m.innerHTML=miniSVG(w,live,m._ids,m.clientWidth>0&&m.clientWidth<520)}
