/* chats (per viewer, this browser) */
const T0=Date.now()-864e5;
const EX={id:"example",no:13,title:"Belmont drapery refit",example:true,ts:T0,turns:[
 {role:"user",ts:T0,content:"Belmont Hotel wants 40 guest rooms refitted with blackout drapery and ceiling track before December. Scope it, price it roughly, flag contract risks, and recommend how we proceed."},
 {role:"assistant",ts:T0+94000,content:"### Recommendation\nRun it as a **phased programme**: two floors in November, the remaining rooms in December once samples are approved. A single December push leaves no room for a late sample sign-off.\n\n### Indicative budget\n| Line | Per room | 40 rooms |\n|---|---|---|\n| Drapery, track, installation | PHP 22,050 | PHP 882,000 |\n| Contingency 8% | | PHP 70,560 |\n| **Indicative total, before VAT** | | **PHP 952,560** |\n\n### Before we quote\n- Guaranteed room blocks from Belmont, in writing\n- Delay clause wording agreed with counsel\n- Your approval of the phased schedule and contingency",
  ex:{facts:[{label:"Indicative total",value:"PHP 952,560",note:"Before VAT"},{label:"Per room",value:"PHP 22,050"},{label:"Lead time",value:"5–7 weeks",note:"Unverified canvass"}],charts:[{type:"bar",title:"Cost per room, by line",unit:"PHP",labels:["Drapery","Ceiling track","Installation"],series:[{name:"Per room",values:[11650,8000,2400]}],note:"Mid-range rates; drapery is more than half of every room."}],matrix:{title:"Three ways to schedule it",columns:["Risk","Disruption","Finish"],rows:[{name:"Full December push",cells:[2,4,"Dec 20"]},{name:"Phased (recommended)",cells:[4,3,"Dec 12"]},{name:"January start",cells:[5,2,"Feb 6"]}],note:"Ratings out of five; higher is better."},sources:[{title:"Visayas fit-out rate cards, 2026 Q3",note:"verified"},{title:"Staff canvass, Iloilo",note:"unverified"}]},
  work:{ms:94000,firewall:"clear",steps:[{role:"research",tier:"medium",focus:"Local rates",task:"Iloilo rates and lead times for drapery and track",v:"pass",ms:14000,out:"Blackout drapery, hotel grade: PHP 9,500–13,800 per window (verified).\nCeiling track: PHP 2,100–2,900 per metre (verified).\nLead time 5–7 weeks (staff canvass, unverified).\nCONFIDENCE: medium"},{role:"finance",tier:"high",focus:"Forty-room budget",after:[1],task:"An indicative budget for forty rooms",v:"pass",ms:38000,out:"Per room PHP 22,050. 40 rooms PHP 882,000. Contingency 8% PHP 70,560. Total PHP 952,560 before VAT.\nCONFIDENCE: medium"},{role:"legal",tier:"high",focus:"Deadline exposure",task:"Contract risks behind a December deadline",v:"pass",ms:33000,out:"Cap liquidated damages at 10%; exclude delay from late sample approval; variations by signed order only. Counsel: LD wording.\nCONFIDENCE: high"},{role:"decision",tier:"medium",focus:"Schedule choice",after:[2,3],task:"How the company should proceed",v:"pass",ms:21000,out:"Recommend phased. Options: full push, phased, January start. You decide the schedule and contingency.\nCONFIDENCE: high"}],
  map:{kind:"hotel fit-out, scope and price",rationale:"Rates, a budget, contract risk and a recommendation each need their own desk.",thinking:["Forty rooms before December: nothing can be priced until local rates are in.","The budget will clear PHP 500,000, so finance works at deep effort.","A hard deadline brings delay exposure; legal can read it in parallel.","Once the budget and the risks are known, an arbiter desk weighs the schedule."],calls:[],pages:[]},
  flow:[0,2,6,9,7,4,8,12,15,11,9,6,10,14,9,5,3,6,8,4,2,1],
  feed:[[400,null,"Received the brief: about 45 tokens."],[1600,null,"Classified the brief: <em>hotel fit-out, scope and price</em>."],[1700,null,"Rates, a budget, contract risk and a recommendation each need their own desk."],[1800,"Commissioned <em>four desks</em>","Commissioned four desks."],[2000,null,"Opened desk I: research desk at <em>considered</em> effort, local rates and lead times."],[2240,null,"Opened desk II: finance desk at <em>deep</em> effort, budget over PHP 500,000."],[2480,null,"Desk II waits for desk I."],[2720,null,"Opened desk III: legal desk at <em>deep</em> effort, deadline exposure."],[2960,null,"Opened desk IV: arbiter desk at <em>considered</em> effort, choose a schedule."],[16200,"The research desk filed its notes","Desk I filed 48 tokens of notes in 14 s."],[38400,"The finance desk filed its notes","Desk II filed 30 tokens of notes in 38 s."],[39800,"The legal desk filed its notes","Desk III filed 36 tokens of notes in 33 s."],[41000,"All four passed review","Review: all four pieces pass."],[88000,"Set the exhibits","Set the exhibits: three figures, one chart, a comparison, sources."],[91200,"Firewall clear","Firewall: clear. Nothing restricted leaves with this answer."],[94000,"Delivered","Delivered in 1 min 34 s."]]}}]};
let chats=KV.get("chats",null)||[];const withEx=()=>{if(!chats.find(c=>c.id==="example")&&!KV.get("noExample",null))chats.push(EX)};withEx();let cur=null;
const save=()=>KV.put("chats",chats);const nextNo=()=>Math.max(13,...chats.map(c=>c.no||0))+1;
