const sampleWork=()=>{let best=null;for(const c of chats){if(c.archived)continue;for(const t of c.turns){const w=t.work;if(!w||!(w.steps||[]).length)continue;const sc=(w.steps.length)+((w.map&&w.map.pages||[]).length?20:0);if(!best||sc>best.sc)best={w,sc}}}return best?best.w:EX.turns[1].work};
const cardHTML=(attrs,pv,name,sub,desc)=>`<button type="button" class="card" role="radio" aria-checked="false" ${attrs}><span class="pv">${pv}</span><span class="nm"><i></i>${name}${sub?`<small>${sub}</small>`:""}</span>${desc?`<span class="ds">${desc}</span>`:""}</button>`;
const swRow=(k,name,desc)=>`<button type="button" class="srow" role="switch" aria-checked="false" data-sw="${k}"><span class="l"><b>${name}</b><small>${desc}</small></span><span class="sw2"></span></button>`;
const uiHTML=c=>`<span class="ui ${c}"><i class="s"></i><i class="t"></i><i class="c"></i><i class="k"></i></span>`;
/* small diagrams for the staffing and map choices, drawn in the page's own tokens */
const dia=(desks)=>{const o=[18,41];let g=`<circle cx="${o[0]}" cy="${o[1]}" r="6" fill="var(--ink)"/>`;desks.forEach(([x,y,c],i)=>{g=`<line x1="${o[0]}" y1="${o[1]}" x2="${x}" y2="${y}" stroke="var(--line-3)" stroke-width=".8"/>`+g+`<circle cx="${x}" cy="${y}" r="${3.4+(i%3)}" fill="${c}"/>`});return `<svg viewBox="0 0 150 82" preserveAspectRatio="xMidYMid meet">${g}</svg>`};
const DIA={auto:dia([[70,22,"var(--s1)"],[82,46,"var(--s1)"],[66,66,"var(--s2)"]]),always:dia([[62,14,"var(--s1)"],[84,26,"var(--s1)"],[98,44,"var(--s2)"],[88,62,"var(--s4)"],[64,72,"var(--s5)"],[112,70,"var(--s3)"]]),off:`<svg viewBox="0 0 150 82"><circle cx="18" cy="41" r="6" fill="var(--ink)"/><line x1="26" y1="41" x2="120" y2="41" stroke="var(--gold)" stroke-width=".8" stroke-dasharray="2 3"/><rect x="122" y="35" width="14" height="12" rx="2" fill="none" stroke="var(--n-rim)"/></svg>`};
const THUMB={flow:`<svg viewBox="0 0 150 82"><rect x="8" y="34" width="28" height="14" rx="2" fill="var(--n-hollow)" stroke="var(--n-rim)" stroke-width=".6"/>${[12,34,56].map(y=>`<path d="M36 41C50 41 50 ${y+7} 62 ${y+7}" fill="none" stroke="var(--line-3)" stroke-width=".7"/><rect x="62" y="${y}" width="38" height="14" rx="2" fill="var(--n-hollow)" stroke="var(--n-rim)" stroke-width=".6"/><path d="M100 ${y+7}C112 ${y+7} 110 41 118 41" fill="none" stroke="var(--line-3)" stroke-width=".7"/>`).join("")}<rect x="118" y="34" width="24" height="14" rx="2" fill="var(--panel)" stroke="var(--gold)" stroke-width=".7"/></svg>`,
 field:`<svg viewBox="0 0 150 82"><g stroke="var(--line-3)" stroke-width=".7"><line x1="30" y1="44" x2="62" y2="20"/><line x1="30" y1="44" x2="70" y2="50"/><line x1="30" y1="44" x2="52" y2="68"/><line x1="70" y1="50" x2="108" y2="40"/><line x1="62" y1="20" x2="108" y2="40"/><line x1="108" y1="40" x2="136" y2="22"/><line x1="108" y1="40" x2="138" y2="56"/><line x1="108" y1="40" x2="124" y2="70"/></g><circle cx="30" cy="44" r="7" fill="var(--ink)"/><circle cx="62" cy="20" r="5" fill="var(--s1)"/><circle cx="70" cy="50" r="6.5" fill="var(--s1)"/><circle cx="52" cy="68" r="4" fill="var(--s4)"/><circle cx="108" cy="40" r="6" fill="var(--panel)" stroke="var(--gold)"/><circle cx="136" cy="22" r="3" fill="var(--n-hollow)" stroke="var(--n-rim)"/><circle cx="138" cy="56" r="3.6" fill="var(--n-hollow)" stroke="var(--n-rim)"/><circle cx="124" cy="70" r="2.6" fill="var(--n-hollow)" stroke="var(--n-rim)"/></svg>`};
const SAMPLE=`<div class="ans"><h3>Recommendation</h3><p>Run it as a <strong>phased programme</strong>: two floors in November, the rest in December once samples are approved.</p></div>`;
function paneHTML(t){
 if(t==="general")return `<h3>General</h3><p class="lede">How EXPIRA addresses you, and the keys that move you around.</p>
  <div class="grp"><div class="gh"><span><b>Your name</b><small>Used in the greeting on the start page.</small></span><input class="tin" data-name maxlength="24" value="${esc(PREF.name)}" aria-label="Your name" spellcheck="false"></div>
  <div class="pvbox"><span class="cap">Preview</span><p class="gp" id="pvGreet"></p></div></div>
  <div class="grp"><div class="gh"><span><b>Keyboard</b><small>Everything also lives in the command palette, ⌘K.</small></span></div><dl class="kbl">${[["⌘K","Commands"],["⌘,","Settings"],["⌥N","New chat"],["⌥L","The Dispatch"],["F2","Rename this chat"],["/","Search chats"],["Esc","Stop the run, or close"],["?","Shortcut sheet"]].map(([k,d])=>`<dt><span class="kb">${k}</span></dt><dd>${d}</dd>`).join("")}</dl></div>`;
 if(t==="appearance")return `<h3>Appearance</h3><p class="lede">Palette, type and pace. Changes apply as you choose them.</p>
  <div class="grp"><div class="gh"><span><b>Theme</b><small>System follows your device.</small></span></div><div class="cards">
   ${cardHTML('data-th="system"',uiHTML("th-l")+uiHTML("th-d half"),"System")}${cardHTML('data-th="light"',uiHTML("th-l"),"Light")}${cardHTML('data-th="dark"',uiHTML("th-d"),"Dark")}</div></div>
  <div class="grp"><div class="gh"><span><b>Text size</b><small>For answers and your briefs.</small></span></div><div class="cards">
   ${[["s","Small",15],["m","Default",19],["l","Large",24]].map(([v,n,px])=>cardHTML(`data-pk="text" data-v="${v}"`,`<span class="aa" style="font-size:${px}px">Aa</span>`,n)).join("")}</div>
   <div class="pvbox" style="margin-top:12px"><span class="cap">Preview</span>${SAMPLE}</div></div>
  <div class="grp"><div class="gh"><span><b>Density</b><small>Space between and inside messages.</small></span></div><div class="cards two">
   ${cardHTML('data-pk="density" data-v="comfortable"',`<span class="dn" style="gap:9px"><i style="height:22px"></i><i style="height:22px"></i></span>`,"Comfortable")}${cardHTML('data-pk="density" data-v="compact"',`<span class="dn" style="gap:4px"><i style="height:16px"></i><i style="height:16px"></i><i style="height:16px"></i></span>`,"Compact")}</div></div>
  <div class="grp"><div class="gh"><span><b>Motion</b><small>Calm keeps every change instant.${MQR.matches?" Your device asks for reduced motion, so motion stays calm.":""}</small></span></div><div class="cards two">
   ${cardHTML('data-pk="motion" data-v="full"','<span class="pv-in full" style="position:absolute;inset:0"><span class="mo"></span></span>',"Full","","Soft-close easing, blur-ins, the live map")}${cardHTML('data-pk="motion" data-v="calm"','<span style="position:absolute;inset:0"><span class="mo"></span></span>',"Calm","","No animation anywhere")}</div></div>
  ${swRow("grain","Film grain on the mark","The 24 fps grain on the start page's mark.")}`;
 if(t==="briefs")return `<h3>Briefs</h3><p class="lede">How the orchestrator staffs each brief. The same choices sit beside the composer.</p>
  <div class="grp"><div class="gh"><span><b>Staffing</b><small>How many desks, and which, is the orchestrator's call in Auto.</small></span></div><div class="cards">
   ${cardHTML('data-so="desks" data-v="auto"',DIA.auto,"Auto","","Staffs each brief itself")}${cardHTML('data-so="desks" data-v="always"',DIA.always,"Thorough","","Always desks, split generously")}${cardHTML('data-so="desks" data-v="off"',DIA.off,"Direct","","No desks; fastest")}</div></div>
  <div class="grp"><div class="gh"><span><b>Depth</b><small>Where desks start on the effort scale.</small></span></div><div class="cards two">
   ${cardHTML('data-so="depth" data-v="standard"',`<span class="aa">${meter("medium")}</span>`,"Standard","","Each desk starts at its floor")}${cardHTML('data-so="depth" data-v="deep"',`<span class="aa">${meter("high")}</span>`,"Deep","","Every desk runs deep")}</div></div>
  <div class="grp"><div class="gh"><span><b>Freshness</b><small>How recent web sources should be. Results always come newest first, with today's date in every brief.</small></span></div><div class="cards">
   ${[["3","90 days",.2],["12","12 months",.55],["any","Any date",1]].map(([v,n,f])=>cardHTML(`data-so="fresh" data-v="${v}"`,`<svg viewBox="0 0 150 82"><line x1="14" y1="50" x2="136" y2="50" stroke="var(--line-3)" stroke-width=".8"/><rect x="${136-122*f}" y="44" width="${122*f}" height="12" rx="2" fill="var(--gold-wash)" stroke="var(--gold)" stroke-width=".7"/>${[0,1,2,3,4,5,6].map(k=>`<circle cx="${20+k*18}" cy="${34-((k*37)%11)}" r="2.4" fill="${20+k*18>=136-122*f?"var(--gold)":"var(--n-rim)"}"/>`).join("")}<text x="136" y="72" text-anchor="end" font-size="8" fill="var(--mute)" font-family="Inter,system-ui">today</text></svg>`,n)).join("")}</div></div>
  ${swRow("safe","Client-safe","Firewall-check every answer and exhibit before it is filed.")}
  ${swRow("web","Web research",WEB.ok?"Research and legal desks can search with Exa.":"Connect Exa in claude.ai to enable.")}`;
 if(t==="map")return `<h3>The map</h3><p class="lede">How each run is drawn: a plate in columns, or a field under gravity.</p>
  <div class="grp"><div class="gh"><span><b>Default view</b><small>Either can be switched on any map.</small></span></div><div class="cards two">
   ${cardHTML('data-mvd="flow"',THUMB.flow,"Flow","","Columns: orchestrator, desks, connector, sources")}${cardHTML('data-mvd="field"',THUMB.field,"Field","","Gravity: size is tokens, weight is traffic")}</div></div>
  <div class="grp"><div class="gh"><span><b>Forces</b><small>The field's four forces, after Obsidian's graph view.</small></span><button class="btn2" data-reset-forces>Reset</button></div>
   <div class="mapw pvmap" id="pvMap" style="margin-bottom:16px"></div>
   ${[["center","Centre force"],["repel","Repel force"],["link","Link force"],["dist","Link distance"]].map(([k,n])=>`<div class="frc"><label for="f_${k}">${n}</label><input type="range" id="f_${k}" data-force="${k}" min="0.3" max="2" step="0.05" value="${FORCES[k]}" style="--p:${((FORCES[k]-.3)/1.7*100).toFixed(1)}%"><output class="num">${(+FORCES[k]).toFixed(2)}×</output></div>`).join("")}</div>`;
 if(t==="files"){const L=allDocs();return `<h3>Files</h3><p class="lede">Every document the console has built, newest first. Each downloads as a self-contained HTML file with the brand assets embedded.</p>
  ${L.length?`<ul class="flist">${L.map(x=>`<li><span><b>${esc(x.d.title||DOCT[x.d.type])}</b><small>${esc(DOCT[x.d.type]||"")} · ${x.d.pages||"?"} pages · ${esc(new Date(x.ts).toLocaleDateString("en-PH",{day:"numeric",month:"short",year:"numeric"}))} · ${esc(x.c.title)}</small></span><span class="fa"><button type="button" class="btn2" data-fopen="${esc(x.c.id)}|${x.k}">Open</button><button type="button" class="btn2" data-fsave="${esc(x.c.id)}|${x.k}" style="border-color:var(--ink)">Download</button></span></li>`).join("")}</ul>`:`<p class="empty2">No documents yet. Choose one with the Document button beside the message box, or ask for one in a brief: “Prepare a quotation for…”.</p>`}
  <div class="grp"><div class="gh"><span><b>Templates</b><small>The kernel's six templates, unfilled, are in Settings → Kernel.</small></span><button type="button" class="btn2" data-tab="kernel">Kernel</button></div></div>`}
 if(t==="kernel"){const K=KLIB.v;return `<h3>Kernel</h3><p class="lede">The GSSC master kernel lives inside the console: its doctrine, the tokenized quotation master, the brand assets and every derivative. Documents are built from it, not from files you attach.</p>
  <div class="grp"><div class="gh"><span><b>${K?`Kernel ${esc(K.kernel_version)}`:"Loading the kernel…"}</b><small>${K?`${Object.keys(K.kernel).length} modules · ${K.derivatives.length} derivatives · ${Object.keys(K.brand_assets).length} brand assets`:""}</small></span></div><div class="kver" id="kVer"><span>Checking asset hashes…</span></div></div>
  <div class="grp"><div class="gh"><span><b>Templates</b><small>Open any template hydrated, exactly as the builder makes it. Ask for a document in a brief and the console fills one from these.</small></span></div><ul class="ktpl">${K?K.derivatives.map(d=>`<li><span>${esc(DOCT[d.type]||d.type)}<small>${esc(d.file)}${d.governing?` · ${esc(d.governing)}`:""}</small></span><button type="button" class="btn2" data-ktpl="${esc(d.file)}">Open</button></li>`).join(""):""}</ul></div>
  <div class="grp"><div class="gh"><span><b>Modules</b><small>What each desk reads: finance reads 06 and 14; legal reads 09 and 02; the firewall reads 04; documents follow 08, 10 and 17.</small></span></div><ul class="kmods">${K?Object.entries(K.kernel).map(([id,m])=>`<li><b><span class="num">${esc(id.slice(0,2))}</span>${esc(id.slice(3).replace(/_/g," "))}</b>${esc(String(m.purpose||m.role||"").slice(0,110))}</li>`).join(""):""}</ul></div>`}
 if(t==="library"){const A=chats.filter(c=>c.archived),L=chats.filter(c=>!c.archived&&!c.example);
  return `<h3>Library</h3><p class="lede">Chats and folders are kept in this browser only.</p>
  <div class="stats3"><div><b class="num">${L.length}</b><span class="cap">Chats</span></div><div><b class="num">${FOLDERS.length}</b><span class="cap">Folders</span></div><div><b class="num">${A.length}</b><span class="cap">Archived</span></div></div>
  <div class="grp"><div class="gh"><span><b>Archived chats</b><small>Restore one to bring it back to the sidebar.</small></span></div>${A.length?`<ul class="alist">${A.map(c=>`<li><span>${esc(c.title)}<small class="num">${esc(new Date(c.ts||Date.now()).toLocaleDateString("en-PH",{day:"numeric",month:"short"}))}</small></span><button class="ab" data-unarch="${esc(c.id)}">Restore</button><button class="ab danger" data-purge="${esc(c.id)}">Delete</button></li>`).join("")}</ul>`:`<p class="empty2">Nothing archived.</p>`}</div>
  <div class="srow" style="cursor:default"><span class="l"><b>Copy the library</b><small>Every chat, as JSON, to your clipboard.</small></span><button class="btn2" data-export>Copy JSON</button></div>
  <div class="srow" style="cursor:default"><span class="l"><b>Clear the library</b><small>Deletes every chat and folder in this browser. This cannot be undone.</small></span><button class="btn2 danger" data-clear>Clear</button></div>`}
 return `<h3>About</h3><p class="lede">EXPIRA Console, version 20. Built on Claude for EXPIRA AI Systems and GSSC Integrated Corporation.</p>
  <dl class="about"><dt>Orchestrator</dt><dd>Opus 5.5 at high effort; plans, staffs and decides at the complex tier</dd><dt>Desks</dt><dd>Deep effort at the complex tier by default; considered at the default tier for low-level work only</dd>
  <dt>Claude</dt><dd class="${sample?"ok":"no"}">${sample?"Linked":"Not linked. Open this page in Claude to brief EXPIRA."}</dd><dt>Exa</dt><dd class="${WEB.ok?"ok":"no"}">${WEB.ok?"Connected":"Not connected"}</dd>
  <dt>Truth</dt><dd>The decision agent staffs the desks, then weighs every claim they file against the pages read; the answer cites the ledger; an auditor checks each factual line before filing</dd><dt>Kernel</dt><dd>The GSSC kernel ships inside the console; desks read the doctrine that governs them, and documents are built by a port of the kernel's own builder, checked byte for byte against it</dd><dt>Freshness</dt><dd>Every prompt carries today's date; web results are sorted newest first and anything older than the window is flagged</dd><dt>Policy</dt><dd>Escalates above PHP 500,000; at most two redos; a firewall on client-facing answers</dd><dt>Storage</dt><dd>Chats in this browser; run summaries in the runs log</dd></dl>
  <p class="credit legal">Claude and Anthropic are trademarks of Anthropic, PBC. EXPIRA Console runs on Claude through the Claude app; it is built by EXPIRA AI Systems and is not affiliated with or endorsed by Anthropic.</p>
  <p class="credit">The field view follows Obsidian's graph forces on a d3-force style integrator. Nodes are born as liquid after Hiroyuki Sato's metaball, as Varun Vachhar explains it.</p>`}
function syncStg(){const m=$("#setMenu");
 m.querySelectorAll("[data-th]").forEach(b=>b.setAttribute("aria-checked",String(b.dataset.th===THEME)));
 m.querySelectorAll("[data-pk]").forEach(b=>b.setAttribute("aria-checked",String(PREF[b.dataset.pk]===b.dataset.v)));
 m.querySelectorAll("[data-so]").forEach(b=>b.setAttribute("aria-checked",String(OPT[b.dataset.so]===b.dataset.v)));
 m.querySelectorAll("[data-mvd]").forEach(b=>b.setAttribute("aria-checked",String(VIEW===b.dataset.mvd)));
 m.querySelectorAll("[data-sw]").forEach(b=>{const k=b.dataset.sw;b.setAttribute("aria-checked",String(k==="grain"?!!PREF.grain:k==="safe"?!!OPT.safe:!!(OPT.web&&WEB.ok)));if(k==="web")b.setAttribute("aria-disabled",String(!WEB.ok))});
 const g=$("#pvGreet");if(g)g.innerHTML=esc(greetText().replace(/, [^,]*$/,", "))+`<em>${esc(PREF.name||"Duke")}</em>`;
 m.querySelectorAll(".pv-in").forEach(x=>x.classList.toggle("full",!reduce));m.querySelectorAll(".pv-in .mo").forEach(x=>x.style.setProperty("--w",x.clientWidth+"px"))}
function stab(t){STAB=t;const m=$("#setMenu");m.querySelectorAll("[role=tab]").forEach(b=>b.setAttribute("aria-selected",String(b.dataset.tab===t)));
 FM.forEach(x=>{if(x.opt.pv)x.kill()});const p=$("#stgP");p.innerHTML=`<div class="sp">${paneHTML(t)}</div>`;p.scrollTop=0;syncStg();
 if(t==="kernel"){if(!KLIB.v)KLIB.load().then(()=>{if(STAB==="kernel")stab("kernel")}).catch(()=>{const v=$("#kVer");if(v)v.innerHTML=`<span class="bad">The kernel library could not be loaded.</span>`});else(async()=>{const K=KLIB.v,out=[];for(const [n,a] of Object.entries(K.brand_assets)){const ok=await kSha(kB64(a.base64))===a.sha256_of_decoded_image;out.push(`<span class="${ok?"ok":"bad"}">${esc(n)} ${ok?"verified":"MISMATCH"}</span>`)}const ok2=await kSha(new TextEncoder().encode(K.template))===K.assembly.verification.tokenized_template_sha256;out.unshift(`<span class="${ok2?"ok":"bad"}">Tokenized master ${ok2?"verified":"MISMATCH"}</span>`);const v=$("#kVer");if(v)v.innerHTML=out.join("")})()}
 if(t==="map"){const w=sampleWork();new FieldMap($("#pvMap"),()=>w,{replay:true,pv:true})}}
function applyPrefs(){root.dataset.text=PREF.text;root.dataset.density=PREF.density;root.classList.toggle("calm",PREF.motion==="calm");reduce=MQR.matches||PREF.motion==="calm";GRAIN.run(!cur&&PREF.grain&&!reduce);$("#stage").classList.toggle("grain",!!PREF.grain)}
function reheat(){FM.forEach(m=>{if(m instanceof FieldMap){m.alpha=Math.max(m.alpha,.7);m.sync()}})}
const sure=(b,label,go)=>{if(b.classList.contains("sure")){go();return}const t=b.textContent;b.classList.add("sure");b.textContent=label;clearTimeout(b._t);b._t=setTimeout(()=>{b.classList.remove("sure");b.textContent=t},3200)};
$("#setMenu").addEventListener("click",e=>{
 const tb=e.target.closest("[data-tab]");if(tb){stab(tb.dataset.tab);return}
 const th=e.target.closest("[data-th]");if(th){applyTheme(th.dataset.th,true);syncStg();return}
 const pk=e.target.closest("[data-pk]");if(pk){PREF[pk.dataset.pk]=pk.dataset.v;savePref();applyPrefs();syncStg();return}
 const sw=e.target.closest("[data-sw]");if(sw){const k=sw.dataset.sw;if(k==="grain"){PREF.grain=!PREF.grain;savePref();applyPrefs()}else if(k==="safe"){OPT.safe=!OPT.safe;saveOpt();drawOpt()}else if(k==="web"){if(!WEB.ok)return;OPT.web=!OPT.web;saveOpt();drawOpt()}syncStg();return}
 const so=e.target.closest("[data-so]");if(so){OPT[so.dataset.so]=so.dataset.v;saveOpt();drawOpt();syncStg();return}
 const mv=e.target.closest("[data-mvd]");if(mv){setView(mv.dataset.mvd);syncStg();return}
 if(e.target.closest("[data-reset-forces]")){Object.assign(FORCES,{center:1,repel:1,link:1,dist:1});savePref();$("#setMenu").querySelectorAll("[data-force]").forEach(r=>{r.value=1;r.style.setProperty("--p",(.7/1.7*100).toFixed(1)+"%");r.nextElementSibling.textContent="1.00×"});reheat();return}
 const ua=e.target.closest("[data-unarch]");if(ua){const c=chats.find(x=>x.id===ua.dataset.unarch);if(c){c.archived=false;save();renderRecents();stab("library")}return}
 const pg=e.target.closest("[data-purge]");if(pg){sure(pg,"Confirm",()=>{const i=chats.findIndex(x=>x.id===pg.dataset.purge);if(i>=0){chats.splice(i,1);save();renderRecents();stab("library")}});return}
 const ex=e.target.closest("[data-export]");if(ex){const t=JSON.stringify({chats:chats.filter(c=>!c.example),folders:FOLDERS},null,1);const done=m=>{ex.textContent=m;clearTimeout(ex._t);ex._t=setTimeout(()=>ex.textContent="Copy JSON",1800)};navigator.clipboard?navigator.clipboard.writeText(t).then(()=>done("Copied"),()=>done("Not allowed")):done("Not allowed");return}
 const cl=e.target.closest("[data-clear]");if(cl){sure(cl,"Clear everything",()=>{chats.splice(0,chats.length,...chats.filter(c=>c.example));FOLDERS.splice(0,FOLDERS.length);save();saveF();open(null);stab("library")});return}});
$("#setMenu").addEventListener("input",e=>{const n=e.target.closest("[data-name]");if(n){PREF.name=n.value.trim().slice(0,24)||"";savePref();greetR();syncStg();return}
 const f=e.target.closest("[data-force]");if(f){FORCES[f.dataset.force]=+f.value;f.style.setProperty("--p",((f.value-.3)/1.7*100).toFixed(1)+"%");f.nextElementSibling.textContent=(+f.value).toFixed(2)+"×";savePref();reheat()}});
$("#setMenu").addEventListener("keydown",e=>{const m=$("#setMenu");
 if(e.target.getAttribute("role")==="tab"&&(e.key==="ArrowDown"||e.key==="ArrowUp"||e.key==="ArrowRight"||e.key==="ArrowLeft")){const T=[...m.querySelectorAll("[role=tab]")],i=T.indexOf(e.target),n=T[(i+(e.key==="ArrowDown"||e.key==="ArrowRight"?1:-1)+T.length)%T.length];e.preventDefault();n.focus();stab(n.dataset.tab);return}
 if(e.key==="Tab"){const F=[...m.querySelectorAll('button:not([disabled]),input,[tabindex="0"]')].filter(x=>x.offsetParent);if(!F.length)return;const a=F[0],z=F[F.length-1];if(e.shiftKey&&document.activeElement===a){e.preventDefault();z.focus()}else if(!e.shiftKey&&document.activeElement===z){e.preventDefault();a.focus()}}});
