/* ---------- more forms: ranked bars, stacked, donut, waterfall, ranges, timeline; each animates in its own liquid way ---------- */
const ROW=(lb,v,u,c)=>`<b>${esc(lb)}</b><span>${c?`<i style="background:${c}"></i>`:""}<em class="num">${esc(fmtV(v,u))}</em></span>`;
const FH=(no,title,unit,extra)=>`<div class="fig-h"><span class="no">Fig. ${no}</span><span class="tt">${esc(title)}</span>${unit?`<span class="capt">${esc(unit)}</span>`:""}<button class="tb" data-tv>Table</button><button class="tb" data-png aria-label="Save as PNG">PNG</button></div>${extra||""}<div class="ro">${RO0}</div>`;
const TBL=(head,rows)=>`<div class="tw tv" hidden><table><thead><tr>${head.map(h=>`<th>${esc(h)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`;
const cut=(s,n)=>{s=String(s);return s.length>n?s.slice(0,n-1)+"…":s};
function chartX(sp,type,no){const title=sp.title||"",unit=sp.unit||"",note=sp.note?`<p class="note">${esc(sp.note)}</p>`:"";const id="x"+(++figSeq);let W=640,H=200,body="",tbl="",lg="";
 const labels=(sp.labels||[]).map(String).slice(0,16),S=(sp.series||[]).filter(x=>Array.isArray(x.values)).slice(0,5).map(x=>({name:String(x.name||""),values:labels.map((_,i)=>Number(x.values[i]))}));
 if(type==="hbar"){const v=(S[0]||{values:[]}).values,n=labels.length;if(!n)return "";const RH=22;H=n*RH+14;const lw=150,m={l:lw,r:74},pw=W-m.l-m.r,hi=Math.max(0,...v.filter(x=>!isNaN(x)))||1;
  labels.forEach((lb,i)=>{const y=8+i*RH,w=Math.max(0,(v[i]||0)/hi*pw);body+=`<g class="mk" data-ro="${esc(ROW(lb,v[i],unit,"var(--s1)"))}" style="--i:${i}"><rect class="hr" x="0" y="${y-2}" width="${W}" height="${RH}" fill="transparent"/><text x="${lw-10}" y="${y+11}" text-anchor="end" class="lbl">${esc(cut(lb,24))}</text><rect class="hb" x="${m.l}" y="${y+3}" width="${w}" height="${RH-10}" rx="3" fill="var(--s1)"/><text class="vl num" x="${m.l+w+7}" y="${y+11.5}">${esc(fmtV(v[i],unit))}</text></g>`});
  tbl=TBL(["",S[0]?.name||title],labels.map((lb,i)=>[lb,fmtV(v[i],unit)]))}
 else if(type==="stacked"){const n=labels.length;if(!n||!S.length)return "";const tot=labels.map((_,i)=>S.reduce((a,x)=>a+(isNaN(x.values[i])?0:Math.max(0,x.values[i])),0)),tk=nice(0,Math.max(...tot)),tN=tk[tk.length-1],m={l:54,r:10,t:14,b:26},pw=W-m.l-m.r,ph=H-m.t-m.b,y=v=>m.t+(1-v/tN)*ph,band=pw/n,bw=Math.min(band*.56,56);
  tk.forEach(v=>body+=`<line class="${v===0?"ax":"gl"}" x1="${m.l}" x2="${W-m.r}" y1="${y(v)}" y2="${y(v)}"/><text x="${m.l-8}" y="${y(v)+3}" text-anchor="end">${esc(fmtV(v,""))}</text>`);
  labels.forEach((lb,i)=>{const cx=m.l+band*(i+.5);let acc=0;body+=`<g class="mk stk" style="--i:${i};transform-origin:0 ${y(0)}px">`;S.forEach((x,j)=>{const v=Math.max(0,x.values[i]||0);if(!v)return;const y0=y(acc),y1=y(acc+v);acc+=v;body+=`<rect class="sg" data-ro="${esc(`<b>${esc(lb)}</b><span><i style="background:var(--s${j+1})"></i>${esc(x.name)} <em class="num">${esc(fmtV(v,unit))}</em></span>`)}" x="${cx-bw/2}" y="${y1+1}" width="${bw}" height="${Math.max(0,y0-y1-2)}" rx="${j===S.length-1?3:1}" fill="var(--s${j+1})" style="--j:${j}"/>`});
   body+=`<text class="vl num" x="${cx}" y="${y(tot[i])-5}" text-anchor="middle">${esc(fmtV(tot[i],unit))}</text></g><text x="${cx}" y="${H-8}" text-anchor="middle">${esc(cut(lb,14))}</text>`});
  lg=`<div class="lg">${S.map((x,j)=>`<span><i style="background:var(--s${j+1})"></i>${esc(x.name)}</span>`).join("")}</div>`;tbl=TBL(["",...S.map(x=>x.name),"Total"],labels.map((lb,i)=>[lb,...S.map(x=>fmtV(x.values[i],unit)),fmtV(tot[i],unit)]))}
 else if(type==="donut"){let parts=labels.map((lb,i)=>({lb,v:Math.max(0,Number((S[0]||{values:[]}).values[i])||0)})).filter(p=>p.v>0);if(parts.length<2)return "";if(parts.length>5){const rest=parts.slice(4).reduce((a,p)=>a+p.v,0);parts=parts.slice(0,4).concat([{lb:"Other",v:rest,o:1}])}
  const T=parts.reduce((a,p)=>a+p.v,0);W=640;H=180;const cx=110,cy=90,r=64;let acc=0;
  parts.forEach((p,i)=>{const pct=p.v/T*100,g=parts.length>1?.8:0,c=p.o?"var(--mute)":`var(--s${i+1})`;body+=`<circle class="dn" data-ro="${esc(ROW(p.lb,p.v,unit,c)+`<span class="num">${pct.toFixed(1)}%</span>`)}" cx="${cx}" cy="${cy}" r="${r}" pathLength="100" fill="none" stroke="${c}" stroke-width="18" stroke-dasharray="${Math.max(.1,pct-g)} ${100-Math.max(.1,pct-g)}" stroke-dashoffset="${-acc+25}" style="--da:${Math.max(.1,pct-g)};--i:${i}"/>`;acc+=pct});
  body+=`<text class="dt num" x="${cx}" y="${cy+2}" text-anchor="middle" data-count="${esc(fmtV(T,unit))}">${esc(fmtV(T,unit))}</text><text class="ds" x="${cx}" y="${cy+17}" text-anchor="middle">Total</text>`;
  parts.forEach((p,i)=>{const y=34+i*24,c=p.o?"var(--mute)":`var(--s${i+1})`;body+=`<g class="mk" style="--i:${i}" data-ro="${esc(ROW(p.lb,p.v,unit,c))}"><rect x="232" y="${y-9}" width="380" height="20" fill="transparent"/><rect x="236" y="${y-5}" width="10" height="10" rx="2" fill="${c}"/><text class="lbl" x="256" y="${y+4}">${esc(cut(p.lb,34))}</text><text class="vl num" x="600" y="${y+4}" text-anchor="end">${esc(fmtV(p.v,unit))}  ·  ${(p.v/T*100).toFixed(0)}%</text></g>`});
  tbl=TBL(["","Value","Share"],parts.map(p=>[p.lb,fmtV(p.v,unit),(p.v/T*100).toFixed(1)+"%"]))}
 else if(type==="waterfall"){const v=(S[0]||{values:[]}).values.map(x=>isNaN(x)?0:x);if(!labels.length)return "";const L=[...labels,sp.total||"Total"],n=L.length;let run=0;const st=v.map(d=>{const a=run;run+=d;return[a,run,d]});st.push([0,run,run,1]);
  const all=st.flatMap(s=>[s[0],s[1]]),tk=nice(Math.min(0,...all),Math.max(0,...all)),t0=tk[0],tN=tk[tk.length-1],m={l:58,r:10,t:16,b:30},pw=W-m.l-m.r,ph=H-m.t-m.b,y=q=>m.t+(1-(q-t0)/(tN-t0))*ph,band=pw/n,bw=Math.min(band*.62,58);
  tk.forEach(q=>body+=`<line class="${q===0?"ax":"gl"}" x1="${m.l}" x2="${W-m.r}" y1="${y(q)}" y2="${y(q)}"/><text x="${m.l-8}" y="${y(q)+3}" text-anchor="end">${esc(fmtV(q,""))}</text>`);
  st.forEach((s,i)=>{const cx=m.l+band*(i+.5),top=y(Math.max(s[0],s[1])),bot=y(Math.min(s[0],s[1])),tot=s[3],c=tot?"color-mix(in srgb,var(--ink) 72%,var(--sheet))":s[2]<0?"var(--s4)":"var(--s1)";
   body+=`<g class="mk wf" style="--i:${i}" data-ro="${esc(ROW(L[i],s[2],unit,c)+(tot?"":`<span>running <em class="num">${esc(fmtV(s[1],unit))}</em></span>`))}"><rect x="${cx-band/2}" y="${m.t}" width="${band}" height="${ph}" fill="transparent"/><rect class="wb" x="${cx-bw/2}" y="${top}" width="${bw}" height="${Math.max(1.5,bot-top)}" rx="2" fill="${c}"/><text class="vl num" x="${cx}" y="${top-5}" text-anchor="middle">${esc((s[2]>0&&!tot?"+":"")+fmtV(s[2],unit))}</text></g><text x="${cx}" y="${H-10}" text-anchor="middle"${tot?' class="tl"':""}>${esc(cut(L[i],13))}</text>`;
   if(i<n-1){const nx=m.l+band*(i+1.5);body+=`<line class="wc" style="--i:${i}" x1="${cx+bw/2}" x2="${nx-bw/2}" y1="${y(s[1])}" y2="${y(s[1])}"/>`}});
  tbl=TBL(["","Change","Running"],st.map((s,i)=>[L[i],fmtV(s[2],unit),fmtV(s[1],unit)]))}
 else if(type==="range"){const nz=x=>x==null||x===""?NaN:Number(x),lo=(sp.low||[]).map(nz),hi2=(sp.high||[]).map(nz),mid=(sp.mid||[]).map(nz),n=labels.length;if(!n)return "";const RH=26;H=n*RH+30;const all=[...lo,...hi2].filter(x=>!isNaN(x)),tk=nice(Math.min(...all),Math.max(...all)),t0=tk[0],tN=tk[tk.length-1],m={l:150,r:20},pw=W-m.l-m.r,x=q=>m.l+(q-t0)/(tN-t0)*pw;
  tk.forEach(q=>body+=`<line class="gl" x1="${x(q)}" x2="${x(q)}" y1="6" y2="${H-22}"/><text x="${x(q)}" y="${H-8}" text-anchor="middle">${esc(fmtV(q,""))}</text>`);
  labels.forEach((lb,i)=>{if(isNaN(lo[i])||isNaN(hi2[i]))return;const y=16+i*RH,a=x(lo[i]),b=x(hi2[i]),c=(a+b)/2;body+=`<g class="mk rg" style="--i:${i};--o:${c}px" data-ro="${esc(`<b>${esc(lb)}</b><span><em class="num">${esc(fmtV(lo[i],unit))}</em> to <em class="num">${esc(fmtV(hi2[i],unit))}</em></span>${isNaN(mid[i])?"":`<span>typical <em class="num">${esc(fmtV(mid[i],unit))}</em></span>`}`)}"><rect x="0" y="${y-11}" width="${W}" height="${RH}" fill="transparent"/><text class="lbl" x="${m.l-12}" y="${y+4}" text-anchor="end">${esc(cut(lb,24))}</text><line class="rl" x1="${a}" x2="${b}" y1="${y}" y2="${y}"/><circle class="re" cx="${a}" cy="${y}" r="4.5"/><circle class="re" cx="${b}" cy="${y}" r="4.5"/>${isNaN(mid[i])?"":`<line class="rm" x1="${x(mid[i])}" x2="${x(mid[i])}" y1="${y-6}" y2="${y+6}"/>`}</g>`});
  tbl=TBL(["","Low","High",...(mid.length?["Typical"]:[])],labels.map((lb,i)=>[lb,fmtV(lo[i],unit),fmtV(hi2[i],unit),...(mid.length?[fmtV(mid[i],unit)]:[])]))}
 else if(type==="timeline"){const T=(sp.tasks||[]).filter(t=>t&&t.label!=null&&t.start!=null&&t.end!=null&&!isNaN(+t.start)&&!isNaN(+t.end)&&+t.end>=+t.start).slice(0,12);if(!T.length)return "";const RH=24;H=T.length*RH+32;const tk=nice(Math.min(...T.map(t=>+t.start)),Math.max(...T.map(t=>+t.end))),t0=tk[0],tN=tk[tk.length-1],m={l:160,r:16},pw=W-m.l-m.r,x=q=>m.l+(q-t0)/(tN-t0)*pw;
  tk.forEach(q=>body+=`<line class="gl" x1="${x(q)}" x2="${x(q)}" y1="4" y2="${H-22}"/><text x="${x(q)}" y="${H-8}" text-anchor="middle">${esc(fmtV(q,""))}${q===tN&&unit?" "+esc(unit):""}</text>`);
  T.forEach((t,i)=>{const y=8+i*RH,a=x(+t.start),b=Math.max(a+3,x(+t.end));body+=`<g class="mk tln" style="--i:${i}" data-ro="${esc(`<b>${esc(t.label)}</b><span><em class="num">${esc(fmtV(+t.start,""))}–${esc(fmtV(+t.end,""))}</em> ${esc(unit)}</span>`)}"><rect x="0" y="${y-3}" width="${W}" height="${RH}" fill="transparent"/><text class="lbl" x="${m.l-12}" y="${y+12}" text-anchor="end">${esc(cut(t.label,26))}</text><rect class="tb2" x="${a}" y="${y+2}" width="${b-a}" height="${RH-10}" rx="3" fill="var(--s${(i%5)+1})" style="transform-origin:${a}px 0"/></g>`});
  tbl=TBL(["Task","Start","End"],T.map(t=>[t.label,String(t.start),String(t.end)]))}
 else return "";
 return `<figure class="fig pre fx-${type}">${FH(no,title,unit,lg)}<svg class="ch" data-fig="${id}" viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(title)}">${body}</svg>${tbl}${note}</figure>`}
/* figures come alive when they scroll into view */
const figIn=f=>{if(!f.classList.contains("pre"))return;f.classList.remove("pre");f.classList.add("in");FIGIO.unobserve(f);countUp(f)};const FIGIO=new IntersectionObserver(es=>es.forEach(en=>{if(en.isIntersecting)figIn(en.target)}),{rootMargin:"0px 0px -40px 0px"});
function armFigs(root){(root||document).querySelectorAll(".fig svg.ch").forEach(v=>{let w=v.parentElement;if(!w.classList.contains("chs")){w=document.createElement("div");w.className="chs";v.before(w);w.append(v)}feather(w,"x")});(root||document).querySelectorAll(".fig.pre:not([data-io])").forEach(f=>{f.dataset.io=1;if(reduce){f.classList.remove("pre");return}FIGIO.observe(f);setTimeout(()=>figIn(f),2500)})}
new MutationObserver(()=>armFigs()).observe(document.getElementById("thread"),{childList:true,subtree:true});
/* high-resolution PNG: the figure redrawn at 3× with its computed colours */
async function figPNG(fig,btn){const svg=fig.querySelector("svg.ch");if(!svg)return;const vb=svg.viewBox.baseVal,S=3,cl=svg.cloneNode(true),src=[svg,...svg.querySelectorAll("*")],dst=[cl,...cl.querySelectorAll("*")];
 src.forEach((el,i)=>{const cs=getComputedStyle(el),d=dst[i];["fill","stroke","stroke-width","opacity","font-size","font-family","font-weight","font-style","letter-spacing","stroke-dasharray","stroke-dashoffset","stroke-linecap","paint-order"].forEach(p=>{const v=cs.getPropertyValue(p);if(v)d.style.setProperty(p,v)});d.style.animation="none";d.style.transition="none";d.removeAttribute("class")});
 dst.forEach(d=>{if(d.style)d.style.transform="none"});cl.setAttribute("xmlns","http://www.w3.org/2000/svg");cl.setAttribute("width",vb.width);cl.setAttribute("height",vb.height);
 const img=new Image();await new Promise((ok,no)=>{img.onload=ok;img.onerror=no;img.src="data:image/svg+xml;charset=utf-8,"+encodeURIComponent(new XMLSerializer().serializeToString(cl))});
 const pad=28,th=44,c=document.createElement("canvas");c.width=(vb.width+pad*2)*S;c.height=(vb.height+pad*2+th)*S;const x=c.getContext("2d");x.scale(S,S);const rs=getComputedStyle(document.documentElement),title=fig.querySelector(".fig-h .tt")?.textContent||"Figure";
 x.fillStyle=rs.getPropertyValue("--sheet").trim()||"#fff";x.fillRect(0,0,c.width,c.height);x.fillStyle=rs.getPropertyValue("--gold").trim();x.font='italic 12px "Libre Baskerville",Georgia,serif';x.fillText(fig.querySelector(".fig-h .no")?.textContent||"",pad,pad+10);
 x.fillStyle=rs.getPropertyValue("--ink").trim();x.font='15px "Libre Baskerville",Georgia,serif';x.fillText(title,pad,pad+30);x.drawImage(img,pad,pad+th,vb.width,vb.height);
 const blob=await new Promise(z=>c.toBlob(z,"image/png")),name=(title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"figure")+"@3x.png",t=btn.textContent;
 const dl=await window.claude?.use?.("downloads")??null;try{if(dl){await dl.save({filename:name,data:blob});btn.textContent="Saved"}else{await navigator.clipboard.write([new ClipboardItem({"image/png":blob})]);btn.textContent="Copied"}}catch(e){btn.textContent=e&&e.code==="declined"?"Declined":"Not saved"}setTimeout(()=>btn.textContent=t,1600)}
document.addEventListener("click",e=>{const b=e.target.closest("[data-png]");if(b){const f=b.closest(".fig");if(f)figPNG(f,b).catch(()=>{b.textContent="Not saved";setTimeout(()=>b.textContent="PNG",1600)})}});
window.__ex=(ex)=>exhibitsHTML(ex,true);

{const P=$("#chov");let tm=0,on=null;const hide=()=>{clearTimeout(tm);if(on&&on._rail){INS.leave("chat:"+on.dataset.id);on._rail=0}on=null;if(!P.hidden){P.classList.remove("in");setTimeout(()=>{if(!on)P.hidden=true},180)}};
 const show=el=>{const c=chats.find(x=>x.id===el.dataset.id);if(!c)return;on=el;const us=(c.turns||[]).filter(t=>t.role==="user"),as=(c.turns||[]).filter(t=>t.role==="assistant"),w=as.length?as[as.length-1].work:null,d=new Date(c.ts||Date.now());
  P.innerHTML=`<div class="ch"><span>${esc(d.toLocaleDateString("en-PH",{month:"short",day:"numeric"}))} · ${d.toLocaleTimeString("en-PH",{hour:"numeric",minute:"2-digit"})}</span><span class="cf num">${us.length} brief${us.length===1?"":"s"}</span></div><p class="ct">${esc(c.title)}</p>${us[0]?`<p class="cq">${esc(clip(us[0].content.replace(/^>.*\n+/gm,""),150))}</p>`:""}${w?`<div class="cs">${[(w.steps||[]).length?`<span>${(w.steps||[]).length} desks</span>`:"",w.web?`<span>${w.web} sources</span>`:"",w.ledger&&w.ledger.claims?`<span>${w.ledger.claims.filter(x=>x.v==="supported"||x.v==="derived").length}/${w.ledger.claims.length} grounded</span>`:"",w.doc&&!w.doc.error?`<span>${esc(DOCT[w.doc.type]||"Document")}</span>`:""].filter(Boolean).join("")}</div>`:""}`;
  if(INS.view("chat:"+c.id,`<div class="si cpv">${P.innerHTML}</div>`)){on._rail=1;return}P.hidden=false;const r=el.getBoundingClientRect(),q=P.getBoundingClientRect();P.style.left=Math.min(innerWidth-q.width-12,r.right+10)+"px";P.style.top=Math.max(12,Math.min(innerHeight-q.height-12,r.top+r.height/2-q.height/2))+"px";requestAnimationFrame(()=>P.classList.add("in"))};
 document.addEventListener("pointerover",e=>{const it=e.target.closest?.(".row .item[data-id]");if(it){if(it===on)return;clearTimeout(tm);tm=setTimeout(()=>show(it),on?60:520)}else if(on&&!e.target.closest?.("#chov"))hide()});addEventListener("scroll",hide,true);document.addEventListener("pointerdown",hide,true)}
