/* ---------- exhibits: key figures, charts, a comparison and sources, built from the desks' notes ---------- */
function exhibitsHTML(ex,live){if(!ex)return "";const facts=(ex.facts||[]).filter(f=>f&&f.value!=null).slice(0,4),charts=(ex.charts||[]).slice(0,3),mx=ex.matrix&&Array.isArray(ex.matrix.rows)&&ex.matrix.rows.length?ex.matrix:null,src=(ex.sources||[]).filter(s=>s&&s.title).slice(0,8);
 if(!facts.length&&!charts.length&&!mx&&!src.length)return "";let k=0;const it=h=>`<div class="exi" style="animation-delay:${(k++)*.09}s">${h}</div>`;let o="";
 if(facts.length)o+=it(`<div class="facts">${facts.map(f=>`<div class="fact"><span class="v num" ${live?`data-count="${esc(f.value)}"`:""}>${esc(String(f.value))}</span><span class="lb">${esc(f.label||"")}</span>${f.note?`<span class="nt">${esc(f.note)}</span>`:""}</div>`).join("")}</div>`);
 charts.forEach((c,i)=>{const h=chartFig(JSON.stringify(c),i+1);if(h)o+=it(h)});
 if(mx){const cols=(mx.columns||[]).map(String);o+=it(`<figure class="fig"><div class="fig-h"><span class="no">Table</span><span class="tt">${esc(mx.title||"Comparison")}</span></div><div class="tw"><table class="mx"><thead><tr><th></th>${cols.map(c=>`<th>${esc(c)}</th>`).join("")}</tr></thead><tbody>${mx.rows.slice(0,12).map(r=>`<tr><td class="rh">${esc(r.name||"")}</td>${(r.cells||[]).slice(0,cols.length).map(c=>`<td>${cellHTML(c)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>${mx.note?`<p class="note">${esc(mx.note)}</p>`:""}</figure>`)}
 if(src.length)o+=it(`<div class="srcs"><span class="cap">Sources</span><ol>${src.map(s=>`<li>${/^https?:\/\//.test(s.url||"")?`<a href="${esc(s.url)}" target="_blank" rel="noopener" data-src="${esc(s.url)}">${esc(s.title)}</a><span class="dm">${esc(hostOf(s.url))}</span>`:esc(s.title)}${s.note?` <span class="nt">${esc(s.note)}</span>`:""}</li>`).join("")}</ol></div>`);
 const cnt=[facts.length?`${facts.length} figure${facts.length>1?"s":""}`:"",charts.length?`${charts.length} chart${charts.length>1?"s":""}`:"",mx?"1 table":"",src.length?`${src.length} source${src.length>1?"s":""}`:""].filter(Boolean).join(" · ");
 return `<section class="exh"><button class="exh-h" data-exf aria-expanded="true"><span class="cap">Exhibits</span><span class="cnt">${cnt}</span><span class="ln"></span>${CHEV}</button><div class="exb"><div>${o}</div></div></section>`}
function cellHTML(c){if(typeof c==="number"&&c>=0&&c<=5&&Number.isInteger(c))return `<span class="rate" aria-label="${c} of 5">${[1,2,3,4,5].map(i=>`<i class="${i<=c?"on":""}"></i>`).join("")}</span>`;if(typeof c==="boolean")return c?"Yes":"—";return esc(String(c??"—"))}
/* figures count up once, from zero, with a soft close */
function countUp(root){if(reduce)return;root.querySelectorAll("[data-count]").forEach(el=>{const s=el.dataset.count,m=s.match(/-?[\d,]*\.?\d+/);if(!m)return;const target=parseFloat(m[0].replace(/,/g,"")),dec=(m[0].split(".")[1]||"").length,pre=s.slice(0,m.index),post=s.slice(m.index+m[0].length),t0=performance.now(),D=1100;
 const f=t=>{const p=Math.min(1,(t-t0)/D),e=1-Math.pow(1-p,4),v=target*e;el.textContent=pre+(dec?v.toFixed(dec):Math.round(v).toLocaleString("en-PH"))+post;if(p<1)requestAnimationFrame(f);else el.textContent=s};requestAnimationFrame(f)})}

